version: "3.7"
services:
  v2ray:
    image: v2fly/v2fly-core
    container_name: v2ray
    ports:
      - "127.0.0.1:10000:10000"
    command: run -c /config.json
    volumes:
      - type: bind
        source: ${PWD}/v2ray-server.json
        target: /config.json
        read_only: true
    restart: unless-stopped
  proxy:
    image: caddy
    restart: always
    network_mode: host
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy:/data/
