version: "3.7"
services:
  v2ray:
    image: v2fly/v2fly-core
    container_name: v2ray
    networks:
      - traefik-public
    command: run -c /etc/v2ray/config.json
    volumes:
      - ./v2ray-server.json:/etc/v2ray/config.json:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.v2ray.rule=Host(`vpn.avrdu.de`) && PathPrefix(`/ws`)"
      - "traefik.http.routers.v2ray.entrypoints=websecure"
      - "traefik.http.routers.v2ray.tls=true"
      - "traefik.http.services.v2ray.loadbalancer.server.port=10000"
      - "traefik.http.middlewares.v2ray-ws.headers.customrequestheaders.Connection=Upgrade"
      - "traefik.http.middlewares.v2ray-ws.headers.customrequestheaders.Upgrade=websocket"
      - "traefik.http.routers.v2ray.middlewares=v2ray-ws"
    restart: unless-stopped

networks:
  traefik-public:
    external: true
